### PR TITLE
Pass `metric.reporters` and related settings through to consumer/producer

### PR DESCRIPTION
**Pull request by clayrat**

### CODE REVIEW

**Comment by clayrat** [comment]
@alexandru what do you think about this?

**Comment by Avasil** [comment]
@clayrat I'm no @alexandru and don't know if there was any special rule about stuff in config but I am in favor of exposing every relevant ```Kafka``` configuration

**Comment by clayrat** [comment]
@Avasil ping? We kinda need this feature, any objections to having this?

**Comment by Avasil** [comment]
@clayrat Could you add it for kafka 1.0.0 too?

**Comment by clayrat** [comment]
@Avasil Done

**Comment by Avasil** [comment]
@clayrat Thanks, I'm merging it. Do you need it released soon?

**Comment by clayrat** [comment]
It's not very urgent, but having it within the next couple of weeks would be nice.

**Comment by clayrat** [comment]
Thanks!

**Pull request merged**
