### PR TITLE
[WIP] Allow to pass Properties to Producer/Consumer's constructor

### PR DESCRIPTION
**Pull request by cakper**
Hello guys,

This is just a proposal and I'm more interested in starting a discussion about the way we configure our Producer/Consumer, than insisting on what I'm proposing in this PR.

Problem I've faced is that our configurations got out of sync with the ones that Kafka clients are expecting. I've initially started adding them to out configuration object (https://github.com/cakper/monix-kafka/commit/e3b22fd617343b4950e151b0827716578a882b26#diff-2536a98c12aafbad0c6a66318990bec0R44) but then I've realised that maybe it's not the best way of solving the problem.

Problem is that mapping those configs doesn't really scale and is qute error prone (ie missing properties that I need to use in our 0.11 client, but kafka-monix doesn't expose them).

After a quick chat wit @avasil I've decided to propse a PR (for 0.x series) that will allow us to pass plain Properties if needed, without introducing any breaking changes, which I think I've managed to achive in this PR. I admit way to achieve it is not ideal, but it would unblock me / my company.

Long term (1.0) I'd like to suggest splitting both Kafka's and Monix's configs into two separate objects (or coming up with a solution that would be forward compatible with regards to Kafka clients updates). The way for example akka-streams-kafka handles it is not so bad, so we could have a look for an inspiration.

Please let me guys what you think, and if the direction I'm proposing is something worth discussing I'm happy to finish the PR (scaladocs and site docs).

Kacper

### CODE REVIEW

**Comment by leandrob13** [comment]
I do agree with this, we had gone through the setback described by @cakper before. 

@Avasil  Regarding validating mandatory configs. I do think documentation + the properties file with all the needed default configs could be added. I don't see this being guaranteed through type safety unless we do what we did before and add those to the config objects which is the main problem when working with the lib.

Kacper's approach will be like `know what you are doing` and it won't block people from tweaking the config for precise circumstances. We could also take the safe approach and include the params as we detect them in the config objects but at least we won't let people waiting for a release.

**Comment by cakper** [comment]
> We could also do something like staying with our KafkaConfig and just add methods for adding properties. We could keep user-provided properties in Map and add it in toMap and toProperties. Though we will have to handle the case when user adds property which already exists in the class but it shouldnt be too hard.

I think that's actually might be nicer/simpler solution, do you want me to implement it?

**Comment by Avasil** [comment]
> > We could also do something like staying with our KafkaConfig and just add methods for adding properties. We could keep user-provided properties in Map and add it in toMap and toProperties. Though we will have to handle the case when user adds property which already exists in the class but it shouldnt be too hard.
> 
> I think that's actually might be nicer/simpler solution, do you want me to implement it?

Let's try it!



> As a side note, I will have to cherry pick it to the versions supporting 2.x monix too as I don't think we will be migrating to 3.x anytime soon :)

I can arrange that :)

**Comment by cakper** [comment]
Will do, thanks!

**Comment by cakper** [comment]
Closing as #44 and #45 address the issue in a simpler way

**Pull request closed without merging**
