### PR TITLE
Feature/max poll interval config

### LINKED ISSUE #22: Add max.poll.interval to KafkaConsumerConfig
We ran into a scenario using monix kafka where we needed to use the [Allow consumer to send heartbeats from a background thread](https://cwiki.apache.org/confluence/display/KAFKA/KIP-62%3A+Allow+consumer+to+send+heartbeats+from+a+background+thread) functionality but we were not able to tune the `max.poll.interval` to achieve our goal.

I can create a PR to address this asap.

### PR DESCRIPTION
**Pull request by leandrob13**
Fixes #22 

Adds the `max.poll.interval` configuration to default.conf and `KafkaConsumerConfig`. The motivation is to be able to configure the maximum delay between client calls to poll() considering this: [Allow consumer to send heartbeats from a background thread](https://cwiki.apache.org/confluence/display/KAFKA/KIP-62%3A+Allow+consumer+to+send+heartbeats+from+a+background+thread)

### CODE REVIEW

**Comment by Avasil** [comment]
Tagging @alexandru to get some attention :D 

I have doubts about default ```max.poll.records``` being 1 instead of 500 (kafka default)

@leandrob13 explanation on gitter:

> when you spend too much time processing a record, you want to keep polling kafka to let him know you are alive so when you are finished you tell it to send you one record considering the big amount of time you are spending to process each one
> we defined it having that scenario in mind
> that can be changed as the default value, either way it can always be overriden so no problem in changing it if there are objections
> But you are right, 500 is the recommended value

**Comment by leandrob13** [comment]
@alexandru @Avasil Are there no observations or objections on `max.poll.records` default value?

**Comment by Avasil** [comment]
@leandrob13 @alexandru My opinion is that both ```max.poll.records``` and ```max.poll.interval``` should have the same default as in Kafka documentation to avoid any confusion after upgrading ```monix-kafka``` version.

**Comment by leandrob13** [comment]
@Avasil @alexandru I will change them then, no problem.

**Comment by leandrob13** [comment]
@alexandru @Avasil done guys. Awaiting your decisions.

**Comment by Avasil** [comment]
@leandrob13 Thanks!

**Pull request merged**
