### PR TITLE
Configure serializers in kafka producer after creating

### PR DESCRIPTION
**Pull request by livelxw**

### CODE REVIEW

**Comment by Avasil** [comment]
Thank you @livelxw - are there any errors if it's not done?

**Comment by livelxw** [comment]
No. This should fix the java.lang.NullPointerException error when using io.confluent.kafka.serializers.KafkaAvroSerializer

**Comment by Avasil** [comment]
Sure, thank you once again and let me know if you need a SNAPSHOT version or anything :)

**Comment by livelxw** [comment]
@Avasil Yes, I need a SNAPSHOT version. Thanks!

**Comment by Avasil** [comment]
I released `1.0.0-RC5-14d756d-SNAPSHOT`

You might need to add `resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"` to `build.sbt`

**Pull request merged**
